#import = ["/root/.config/alacritty/catppuccin/catppuccin-mocha.yml"]

[font]
size = 11.5

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.8

[window.padding]
x = 10
y = 10
