#! /bin/sh

xrandr -s 1920x1080

polybar &

fcitx

picom &

#feh --bg-fill --geometry +0-850 ~/Pictures/dona-wallpaper.jpg
#feh --bg-fill ~/Pictures/heavens-official-blessing-wallpaper.jpg
feh --bg-fill ~/Pictures/gray-mountain.jpg

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#~/Documents/coding/video-wallpaper/video-wallpaper.sh dona
